# Generated by Django 5.2.7 on 2025-11-08 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=300)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('games', models.IntegerField()),
                ('mpg', models.FloatField()),
                ('win_share', models.FloatField()),
                ('ppg', models.FloatField()),
                ('ws_48', models.FloatField()),
                ('fg', models.FloatField()),
                ('fga', models.FloatField()),
                ('efg', models.FloatField()),
                ('ast', models.FloatField()),
                ('rbd', models.FloatField()),
                ('fta', models.FloatField()),
                ('ft', models.FloatField()),
                ('ws_rank', models.IntegerField(null=True)),
                ('losses_rank', models.IntegerField(null=True)),
                ('ppg_rank', models.IntegerField(null=True)),
                ('ast_rank', models.IntegerField(null=True)),
                ('trb_rank', models.IntegerField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.team')),
            ],
        ),
    ]
