# Generated by Django 5.2.7 on 2025-11-13 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(unique=True)),
                ('team_name', models.CharField(max_length=300)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('games', models.IntegerField()),
                ('minutes', models.FloatField()),
                ('points', models.IntegerField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('reb', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('ftm', models.IntegerField()),
                ('fg3m', models.IntegerField()),
                ('fg3a', models.IntegerField()),
                ('win_share', models.FloatField(null=True)),
                ('ws_rank', models.IntegerField(null=True)),
                ('losses_rank', models.IntegerField(null=True)),
                ('ppg_rank', models.IntegerField(null=True)),
                ('ast_rank', models.IntegerField(null=True)),
                ('trb_rank', models.IntegerField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.team')),
            ],
        ),
    ]
